### ISSUE TITLE
issue when compiling for tomcat 7

### ISSUE THREAD

**Issue by dualznz** [ajanata/PretendYoureXyzzy#140]
hi i have the latest build of xampp running, installed tomcat 7 & latest java JRE, wen to load up this src ip:8080/cah/WebContent click on take me to the game then i get this thrown at me. not sure what to do, some help would be great thanks.

HTTP Status 500 - Unable to compile class for JSP:

type Exception report

message Unable to compile class for JSP:

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [15] in the generated java file: [C:\xampp\tomcat\work\Catalina\localhost\cah\org\apache\jsp\WebContent\game_jsp.java]
Only a type can be imported. net.socialgamer.cah.data.GameOptions resolves to a package

An error occurred at line: 413 in the jsp file: /WebContent/game.jsp
GameOptions.MIN_SCORE_LIMIT cannot be resolved to a type
410:       <label id="score_limit_template_label" for="score_limit_template">Score limit:</label>
411:       <select id="score_limit_template" class="score_limit">
412:         <%
413:           for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) {
414:         %>
415:           <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
416:         <% } %>

An error occurred at line: 413 in the jsp file: /WebContent/game.jsp
GameOptions.MAX_SCORE_LIMIT cannot be resolved to a type
410:       <label id="score_limit_template_label" for="score_limit_template">Score limit:</label>
411:       <select id="score_limit_template" class="score_limit">
412:         <%
413:           for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) {
414:         %>
415:           <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
416:         <% } %>

An error occurred at line: 415 in the jsp file: /WebContent/game.jsp
GameOptions.DEFAULT_SCORE_LIMIT cannot be resolved to a type
412:         <%
413:           for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) {
414:         %>
415:           <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
416:         <% } %>
417:       </select>
418:       <br/>

An error occurred at line: 423 in the jsp file: /WebContent/game.jsp
GameOptions.MIN_PLAYER_LIMIT cannot be resolved to a type
420:       <select id="player_limit_template" class="player_limit"
421:           aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers.">
422:         <%
423:           for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) {
424:         %>
425:           <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
426:         <% } %>

An error occurred at line: 423 in the jsp file: /WebContent/game.jsp
GameOptions.MAX_PLAYER_LIMIT cannot be resolved to a type
420:       <select id="player_limit_template" class="player_limit"
421:           aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers.">
422:         <%
423:           for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) {
424:         %>
425:           <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
426:         <% } %>

An error occurred at line: 425 in the jsp file: /WebContent/game.jsp
GameOptions.DEFAULT_PLAYER_LIMIT cannot be resolved to a type
422:         <%
423:           for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) {
424:         %>
425:           <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
426:         <% } %>
427:       </select>
428:       Having more than 10 players may get cramped!

An error occurred at line: 434 in the jsp file: /WebContent/game.jsp
GameOptions.MIN_SPECTATOR_LIMIT cannot be resolved to a type
431:       <select id="spectator_limit_template" class="spectator_limit"
432:           aria-label="Spectator limit.">
433:         <%
434:           for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) {
435:         %>
436:           <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
437:         <% } %>

An error occurred at line: 434 in the jsp file: /WebContent/game.jsp
GameOptions.MAX_SPECTATOR_LIMIT cannot be resolved to a type
431:       <select id="spectator_limit_template" class="spectator_limit"
432:           aria-label="Spectator limit.">
433:         <%
434:           for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) {
435:         %>
436:           <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
437:         <% } %>

An error occurred at line: 436 in the jsp file: /WebContent/game.jsp
GameOptions.DEFAULT_SPECTATOR_LIMIT cannot be resolved to a type
433:         <%
434:           for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) {
435:         %>
436:           <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
437:         <% } %>
438:       </select>
439:       Spectators can watch and chat, but not actually play. Not even as Czar.

An error occurred at line: 458 in the jsp file: /WebContent/game.jsp
GameOptions.MIN_BLANK_CARD_LIMIT cannot be resolved to a type
455:       <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer.">
456:         Also include <select id="blanks_limit_template" class="blanks_limit">
457:         <%
458:           for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) {
459:         %>
460:           <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
461:         <% } %>

An error occurred at line: 458 in the jsp file: /WebContent/game.jsp
GameOptions.MAX_BLANK_CARD_LIMIT cannot be resolved to a type
455:       <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer.">
456:         Also include <select id="blanks_limit_template" class="blanks_limit">
457:         <%
458:           for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) {
459:         %>
460:           <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
461:         <% } %>

An error occurred at line: 460 in the jsp file: /WebContent/game.jsp
GameOptions.DEFAULT_BLANK_CARD_LIMIT cannot be resolved to a type
457:         <%
458:           for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) {
459:         %>
460:           <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
461:         <% } %>
462:         </select> blank white cards.
463:       </label>

Stacktrace:
	org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
	org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366)
	org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:485)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:657)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.56 logs.

**Comment by noahp78** [comment]
Having the same issue. looks like it's trying to import something (first error?) "Only a type can be imported. net.socialgamer.cah.data.GameOptions resolves to a package"

**Comment by uecasm** [comment]
Something sounds wrong in your setup.  If you export a WAR file and then install that, then you should be browsing to `http://ip:port/cah/`, which will then take you to `http://ip:port/cah/game.jsp` once you click through the initial page.  In particular `WebContent` should not be a path that exists on a live server, IIRC.

I've had CAH running quite happily on (probably an older version of) Tomcat 7 for quite a while, although admittedly I haven't updated my copy in a few months.

**Comment by dualznz** [comment]
hrmm i might go back to an earlier version, and see what happens how do i do the WAR? there aint that great of documentation for this, im a php dude lol

**Comment by noahp78** [comment]
I fixed my problem with cleaning the workspace, building the maven project
first (maven package) and building it again.

**Comment by dualznz** [comment]
ahh kk how do u build the maven project

**Comment by dualznz** [comment]
ok so i imported it into eclipse, then exported WAR, even created a tomcat server within eclipse and i still get this error thopwn at me

**Comment by ajanata** [comment]
I had a similar problem with Eclipse marking those errors in the jsp files. I believe I fixed that by updating the build path. I don't know why Tomcat would be having a problem.

At this point, you're probably better off using Maven to make the war: mvn clean package war:war

If that has similar problems I can try to take a look at it, but I am about to go on vacation, followed by a busy month of other things. It definitely is working in Tomcat for me, making the war in the manner described: that is how my servers are running.

**Comment by dualznz** [comment]
ok, im going to try it in debian to see if it makes any difference, its annoying though

**Comment by noahp78** [comment]
Are you using eclipse: http://books.sonatype.com/m2eclipse-book/reference/running-sect-running-maven-builds.html

Then just export -> EE -> WAR file and it should export ok.

**Comment by BaltazarSirgue** [comment]
I have the same problem with Eclipse...
I tried to compile with maven, but Tomcat doesn't start anymore : 
```FAIL - Application at context path /cah could not be started```

**Comment by dualznz** [comment]
yup im getting that exact same issue with tomcat Fail to start..

**Comment by noahp78** [comment]
Are you using the latest Tomcat7 version?

**Comment by BaltazarSirgue** [comment]
I think I am. I use the tomcat7 of debian repo.

**Comment by noahp78** [comment]
Last time I checked the tomcat on ubuntu was outdated and also didn't launch. I had to manually download the latest version. It may be the same on debian

**Comment by BaltazarSirgue** [comment]
I will try to compile the last version of tomcat7 this week-end.

**Comment by dualznz** [comment]
ok so i have it all figured out about getting it setup, tired like 10 times on different machines and OS BUT there is an issue in the jsp file game.jsp cant find the resource GAMEOPTIONS. so not sure whats going on there.

**Comment by noahp78** [comment]
now let eclipse build the war using 'export' and it should work (WEB-INF should contain the files)

**Comment by dualznz** [comment]
well i got it all working with no isses in the end just took much longer than i thought, im gonna work on a visual upgrade to this great resource, going to introduce bootstrap into the interface, spice it up abit.

thanks for all ya helps

**Comment by noahp78** [comment]
Please close the issue if it has been fixed :smile:, And good luck with the upgrade!

**Comment by unclepeanuts159** [comment]
How did you fix this? , as I can't clearly see how you have fixed it? as im having the same issue after i get past the agree page I get unable to compile class for jsp

this is what I get :
HTTP Status 500 - Unable to compile class for JSP: An error occurred at line: 15 in the generated java file Only a type can be imported. net.socialgamer.cah.data.GameOptions resolves to a package An error occurred at line: 413 in the jsp file: /game.jsp GameOptions.MIN_SCORE_LIMIT cannot be resolved to a type 410: <label id="score_limit_template_label" for="score_limit_template">Score limit:</label> 411: <select id="score_limit_template" class="score_limit"> 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> An error occurred at line: 413 in the jsp file: /game.jsp GameOptions.MAX_SCORE_LIMIT cannot be resolved to a type 410: <label id="score_limit_template_label" for="score_limit_template">Score limit:</label> 411: <select id="score_limit_template" class="score_limit"> 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> An error occurred at line: 415 in the jsp file: /game.jsp GameOptions.DEFAULT_SCORE_LIMIT cannot be resolved to a type 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> 417: </select> 418: <br/> An error occurred at line: 423 in the jsp file: /game.jsp GameOptions.MIN_PLAYER_LIMIT cannot be resolved to a type 420: <select id="player_limit_template" class="player_limit" 421: aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers."> 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> An error occurred at line: 423 in the jsp file: /game.jsp GameOptions.MAX_PLAYER_LIMIT cannot be resolved to a type 420: <select id="player_limit_template" class="player_limit" 421: aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers."> 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> An error occurred at line: 425 in the jsp file: /game.jsp GameOptions.DEFAULT_PLAYER_LIMIT cannot be resolved to a type 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> 427: </select> 428: Having more than 10 players may get cramped! An error occurred at line: 434 in the jsp file: /game.jsp GameOptions.MIN_SPECTATOR_LIMIT cannot be resolved to a type 431: <select id="spectator_limit_template" class="spectator_limit" 432: aria-label="Spectator limit."> 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> An error occurred at line: 434 in the jsp file: /game.jsp GameOptions.MAX_SPECTATOR_LIMIT cannot be resolved to a type 431: <select id="spectator_limit_template" class="spectator_limit" 432: aria-label="Spectator limit."> 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> An error occurred at line: 436 in the jsp file: /game.jsp GameOptions.DEFAULT_SPECTATOR_LIMIT cannot be resolved to a type 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> 438: </select> 439: Spectators can watch and chat, but not actually play. Not even as Czar. An error occurred at line: 458 in the jsp file: /game.jsp GameOptions.MIN_BLANK_CARD_LIMIT cannot be resolved to a type 455: <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer."> 456: Also include <select id="blanks_limit_template" class="blanks_limit"> 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> An error occurred at line: 458 in the jsp file: /game.jsp GameOptions.MAX_BLANK_CARD_LIMIT cannot be resolved to a type 455: <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer."> 456: Also include <select id="blanks_limit_template" class="blanks_limit"> 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> An error occurred at line: 460 in the jsp file: /game.jsp GameOptions.DEFAULT_BLANK_CARD_LIMIT cannot be resolved to a type 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> 462: </select> blank white cards. 463: </label> Stacktrace:

type Exception report

message Unable to compile class for JSP: An error occurred at line: 15 in the generated java file Only a type can be imported. net.socialgamer.cah.data.GameOptions resolves to a package An error occurred at line: 413 in the jsp file: /game.jsp GameOptions.MIN_SCORE_LIMIT cannot be resolved to a type 410: <label id="score_limit_template_label" for="score_limit_template">Score limit:</label> 411: <select id="score_limit_template" class="score_limit"> 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> An error occurred at line: 413 in the jsp file: /game.jsp GameOptions.MAX_SCORE_LIMIT cannot be resolved to a type 410: <label id="score_limit_template_label" for="score_limit_template">Score limit:</label> 411: <select id="score_limit_template" class="score_limit"> 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> An error occurred at line: 415 in the jsp file: /game.jsp GameOptions.DEFAULT_SCORE_LIMIT cannot be resolved to a type 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> 417: </select> 418: <br/> An error occurred at line: 423 in the jsp file: /game.jsp GameOptions.MIN_PLAYER_LIMIT cannot be resolved to a type 420: <select id="player_limit_template" class="player_limit" 421: aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers."> 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> An error occurred at line: 423 in the jsp file: /game.jsp GameOptions.MAX_PLAYER_LIMIT cannot be resolved to a type 420: <select id="player_limit_template" class="player_limit" 421: aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers."> 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> An error occurred at line: 425 in the jsp file: /game.jsp GameOptions.DEFAULT_PLAYER_LIMIT cannot be resolved to a type 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> 427: </select> 428: Having more than 10 players may get cramped! An error occurred at line: 434 in the jsp file: /game.jsp GameOptions.MIN_SPECTATOR_LIMIT cannot be resolved to a type 431: <select id="spectator_limit_template" class="spectator_limit" 432: aria-label="Spectator limit."> 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> An error occurred at line: 434 in the jsp file: /game.jsp GameOptions.MAX_SPECTATOR_LIMIT cannot be resolved to a type 431: <select id="spectator_limit_template" class="spectator_limit" 432: aria-label="Spectator limit."> 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> An error occurred at line: 436 in the jsp file: /game.jsp GameOptions.DEFAULT_SPECTATOR_LIMIT cannot be resolved to a type 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> 438: </select> 439: Spectators can watch and chat, but not actually play. Not even as Czar. An error occurred at line: 458 in the jsp file: /game.jsp GameOptions.MIN_BLANK_CARD_LIMIT cannot be resolved to a type 455: <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer."> 456: Also include <select id="blanks_limit_template" class="blanks_limit"> 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> An error occurred at line: 458 in the jsp file: /game.jsp GameOptions.MAX_BLANK_CARD_LIMIT cannot be resolved to a type 455: <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer."> 456: Also include <select id="blanks_limit_template" class="blanks_limit"> 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> An error occurred at line: 460 in the jsp file: /game.jsp GameOptions.DEFAULT_BLANK_CARD_LIMIT cannot be resolved to a type 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> 462: </select> blank white cards. 463: </label> Stacktrace:

description The server encountered an internal error (Unable to compile class for JSP: An error occurred at line: 15 in the generated java file Only a type can be imported. net.socialgamer.cah.data.GameOptions resolves to a package An error occurred at line: 413 in the jsp file: /game.jsp GameOptions.MIN_SCORE_LIMIT cannot be resolved to a type 410: <label id="score_limit_template_label" for="score_limit_template">Score limit:</label> 411: <select id="score_limit_template" class="score_limit"> 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> An error occurred at line: 413 in the jsp file: /game.jsp GameOptions.MAX_SCORE_LIMIT cannot be resolved to a type 410: <label id="score_limit_template_label" for="score_limit_template">Score limit:</label> 411: <select id="score_limit_template" class="score_limit"> 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> An error occurred at line: 415 in the jsp file: /game.jsp GameOptions.DEFAULT_SCORE_LIMIT cannot be resolved to a type 412: <% 413: for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) { 414: %> 415: <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 416: <% } %> 417: </select> 418: <br/> An error occurred at line: 423 in the jsp file: /game.jsp GameOptions.MIN_PLAYER_LIMIT cannot be resolved to a type 420: <select id="player_limit_template" class="player_limit" 421: aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers."> 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> An error occurred at line: 423 in the jsp file: /game.jsp GameOptions.MAX_PLAYER_LIMIT cannot be resolved to a type 420: <select id="player_limit_template" class="player_limit" 421: aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers."> 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> An error occurred at line: 425 in the jsp file: /game.jsp GameOptions.DEFAULT_PLAYER_LIMIT cannot be resolved to a type 422: <% 423: for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) { 424: %> 425: <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 426: <% } %> 427: </select> 428: Having more than 10 players may get cramped! An error occurred at line: 434 in the jsp file: /game.jsp GameOptions.MIN_SPECTATOR_LIMIT cannot be resolved to a type 431: <select id="spectator_limit_template" class="spectator_limit" 432: aria-label="Spectator limit."> 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> An error occurred at line: 434 in the jsp file: /game.jsp GameOptions.MAX_SPECTATOR_LIMIT cannot be resolved to a type 431: <select id="spectator_limit_template" class="spectator_limit" 432: aria-label="Spectator limit."> 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> An error occurred at line: 436 in the jsp file: /game.jsp GameOptions.DEFAULT_SPECTATOR_LIMIT cannot be resolved to a type 433: <% 434: for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) { 435: %> 436: <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 437: <% } %> 438: </select> 439: Spectators can watch and chat, but not actually play. Not even as Czar. An error occurred at line: 458 in the jsp file: /game.jsp GameOptions.MIN_BLANK_CARD_LIMIT cannot be resolved to a type 455: <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer."> 456: Also include <select id="blanks_limit_template" class="blanks_limit"> 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> An error occurred at line: 458 in the jsp file: /game.jsp GameOptions.MAX_BLANK_CARD_LIMIT cannot be resolved to a type 455: <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer."> 456: Also include <select id="blanks_limit_template" class="blanks_limit"> 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> An error occurred at line: 460 in the jsp file: /game.jsp GameOptions.DEFAULT_BLANK_CARD_LIMIT cannot be resolved to a type 457: <% 458: for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) { 459: %> 460: <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option> 461: <% } %> 462: </select> blank white cards. 463: </label> Stacktrace:) that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 15 in the generated java file
Only a type can be imported. net.socialgamer.cah.data.GameOptions resolves to a package

An error occurred at line: 413 in the jsp file: /game.jsp
GameOptions.MIN_SCORE_LIMIT cannot be resolved to a type
410:       <label id="score_limit_template_label" for="score_limit_template">Score limit:</label>
411:       <select id="score_limit_template" class="score_limit">
412:         <%
413:           for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) {
414:         %>
415:           <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
416:         <% } %>


An error occurred at line: 413 in the jsp file: /game.jsp
GameOptions.MAX_SCORE_LIMIT cannot be resolved to a type
410:       <label id="score_limit_template_label" for="score_limit_template">Score limit:</label>
411:       <select id="score_limit_template" class="score_limit">
412:         <%
413:           for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) {
414:         %>
415:           <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
416:         <% } %>


An error occurred at line: 415 in the jsp file: /game.jsp
GameOptions.DEFAULT_SCORE_LIMIT cannot be resolved to a type
412:         <%
413:           for (int i = GameOptions.MIN_SCORE_LIMIT; i <= GameOptions.MAX_SCORE_LIMIT; i++) {
414:         %>
415:           <option <%= i == GameOptions.DEFAULT_SCORE_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
416:         <% } %>
417:       </select>
418:       <br/>


An error occurred at line: 423 in the jsp file: /game.jsp
GameOptions.MIN_PLAYER_LIMIT cannot be resolved to a type
420:       <select id="player_limit_template" class="player_limit"
421:           aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers.">
422:         <%
423:           for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) {
424:         %>
425:           <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
426:         <% } %>


An error occurred at line: 423 in the jsp file: /game.jsp
GameOptions.MAX_PLAYER_LIMIT cannot be resolved to a type
420:       <select id="player_limit_template" class="player_limit"
421:           aria-label="Player limit. Having more than 10 players may cause issues both for screen readers and traditional browsers.">
422:         <%
423:           for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) {
424:         %>
425:           <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
426:         <% } %>


An error occurred at line: 425 in the jsp file: /game.jsp
GameOptions.DEFAULT_PLAYER_LIMIT cannot be resolved to a type
422:         <%
423:           for (int i = GameOptions.MIN_PLAYER_LIMIT; i <= GameOptions.MAX_PLAYER_LIMIT; i++) {
424:         %>
425:           <option <%= i == GameOptions.DEFAULT_PLAYER_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
426:         <% } %>
427:       </select>
428:       Having more than 10 players may get cramped!


An error occurred at line: 434 in the jsp file: /game.jsp
GameOptions.MIN_SPECTATOR_LIMIT cannot be resolved to a type
431:       <select id="spectator_limit_template" class="spectator_limit"
432:           aria-label="Spectator limit.">
433:         <%
434:           for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) {
435:         %>
436:           <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
437:         <% } %>


An error occurred at line: 434 in the jsp file: /game.jsp
GameOptions.MAX_SPECTATOR_LIMIT cannot be resolved to a type
431:       <select id="spectator_limit_template" class="spectator_limit"
432:           aria-label="Spectator limit.">
433:         <%
434:           for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) {
435:         %>
436:           <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
437:         <% } %>


An error occurred at line: 436 in the jsp file: /game.jsp
GameOptions.DEFAULT_SPECTATOR_LIMIT cannot be resolved to a type
433:         <%
434:           for (int i = GameOptions.MIN_SPECTATOR_LIMIT; i <= GameOptions.MAX_SPECTATOR_LIMIT; i++) {
435:         %>
436:           <option <%= i == GameOptions.DEFAULT_SPECTATOR_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
437:         <% } %>
438:       </select>
439:       Spectators can watch and chat, but not actually play. Not even as Czar.


An error occurred at line: 458 in the jsp file: /game.jsp
GameOptions.MIN_BLANK_CARD_LIMIT cannot be resolved to a type
455:       <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer.">
456:         Also include <select id="blanks_limit_template" class="blanks_limit">
457:         <%
458:           for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) {
459:         %>
460:           <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
461:         <% } %>


An error occurred at line: 458 in the jsp file: /game.jsp
GameOptions.MAX_BLANK_CARD_LIMIT cannot be resolved to a type
455:       <label id="blanks_limit_label" title="Blank cards allow a player to type in their own answer.">
456:         Also include <select id="blanks_limit_template" class="blanks_limit">
457:         <%
458:           for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) {
459:         %>
460:           <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
461:         <% } %>


An error occurred at line: 460 in the jsp file: /game.jsp
GameOptions.DEFAULT_BLANK_CARD_LIMIT cannot be resolved to a type
457:         <%
458:           for (int i = GameOptions.MIN_BLANK_CARD_LIMIT; i <= GameOptions.MAX_BLANK_CARD_LIMIT; i++) {
459:         %>
460:           <option <%= i == GameOptions.DEFAULT_BLANK_CARD_LIMIT ? "selected='selected' " : "" %>value="<%= i %>"><%= i %></option>
461:         <% } %>
462:         </select> blank white cards.
463:       </label>


Stacktrace:
	org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
	org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:331)
	org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:469)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:378)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:353)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:340)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:646)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.28 logs.

Apache Tomcat/7.0.28

**Comment by noahp78** [comment]
Compile with maven and it should work (mvn package war)

**Comment by unclepeanuts159** [comment]
Look im a real noob in this area so what do i open in Eclipse to change to Maven and how do i get Maven to work?
